spring.application.name=SociusWebBackend
# Port configuration
server.port=8080
# PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://172.29.234.221:5432/sociuswebbackend
spring.datasource.username=postgres
spring.datasource.password=vch11082004
spring.datasource.hikari.data-source-properties.timezone=Ho_Chi_Minh
spring.datasource.driver-class-name=org.postgresql.Driver
#JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#Logging configuration
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#Redis configuration
spring.cache.type=redis
spring.cache.redis.time-to-live=1800000
spring.data.redis.host=172.29.234.221
spring.data.redis.port=6379
spring.data.redis.username=haruya
spring.data.redis.password=vch11082004
spring.data.redis.database=0
#Session configuration
spring.session.store-type=redis
spring.session.redis.namespace=spring:session
spring.session.timeout=30m
spring.session.redis.flush-mode=on-save
spring.session.redis.cleanup-cron=0 0/30 * * * *
#RabbitMQ configuration
spring.rabbitmq.host=172.29.234.221
spring.rabbitmq.port=5672
spring.rabbitmq.username=haruya
spring.rabbitmq.password=vch11082004
spring.rabbitmq.virtual-host=/
#Queue configuration
rabbitmq.exchange.session=session.management
rabbitmq.queue.invalidation=session.invalidation
rabbitmq.routing.invalidate=invalidate.session
#Custom properties
app.cookie.name=SOCIUS_SESSION
app.cookie.path=/
app.cookie.same.site=Lax
app.rbac.key.prefix=rbac:
app.rbac.role.users.prefix=role:users:
app.session.attribute.user_id=USER_ID
app.session.attribute.team_id=TEAM_ID
app.session.attribute.role_id=ROLE_ID
app.session.attribute.spring_id=SPRING.SESSION.ID
redis.cleanup.online-status.interval=300000
redis.cleanup.user-permissions.interval=1800000
redis.cleanup.sessions.interval=3600000
redis.cleanup.cache.interval=3600000