spring.application.name=SociusWebBackend
# Port configuration
server.port=8080
# PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/sociuswebbackend
spring.datasource.username=haruya
spring.datasource.password=vch11082004
spring.datasource.hikari.data-source-properties.timezone=Ho_Chi_Minh
spring.datasource.driver-class-name=org.postgresql.Driver
#JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#Logging configuration
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=off
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.type.descriptor.sql=off
#Redis configuration
spring.cache.type=redis
spring.cache.redis.time-to-live=1800000
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.username=haruya
spring.data.redis.password=vch11082004
spring.data.redis.database=0
#Session configuration
spring.session.redis.namespace=spring:session
spring.session.timeout=60m
spring.session.redis.flush-mode=on-save
spring.session.redis.cleanup-cron=0 0 * * * *
#RabbitMQ configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/
#File upload properties
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
file.upload.dir=./uploads
#Security properties
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true

cors.allowed.origins=http://localhost:3000